# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flacon
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: flacon
  values:
    image:
      repository: ghcr.io/a-gal/docker-flacon
      pullPolicy: IfNotPresent
      tag: "12"
    TZ: Asia/Yekaterinburg
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: flacon.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: false
    resources:
      limits:
        cpu: 10000m
        memory: 8Gi
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 5800
            protocol: http
            targetPort: 5800
        type: ClusterIP
    persistence:
      media:
        enabled: true
        mountPath: /mnt/media
        path: /mnt/wide-one/media
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs

    securityContext:
      # -- Container security context for all containers
      # Can be overruled per container
      container:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        # allowPrivilegeEscalation: false
        # privileged: true
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          add:
            - NET_BIND_SERVICE
            - KILL
        #   drop:
        #     - ALL
        #   # When set to false, it will automatically
        #   # add CHOWN, SETUID, SETGID, FOWNER, DAC_OVERRIDE
        #   # capabilities ONLY when container runs as ROOT
        #   disableS6Caps: false
        # -- PUID for all containers
        # Can be overruled per container
        PUID: 568
        fsGroup: 568
        # -- UMASK for all containers
        # Can be overruled per container
        # UMASK: "0022"

    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: true
                  path: /
                  type: tcp
                readiness:
                  enabled: true
                  path: /
                  type: tcp
                startup:
                  enabled: true
                  path: /
                  type: tcp
        replicas: 1
        type: Deployment
