apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kms
  namespace: kms
spec:
  interval: 15m
  chart:
    spec:
      chart: kms
      version: 19.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: kms
  values:
    TZ: Asia/Yekaterinburg
    service:
      main:
        type: NodePort
