apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kms
  namespace: kms
spec:
  interval: 15m
  chart:
    spec:
      chart: kms
      version: 21.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: kms
  values:
    TZ: Asia/Yekaterinburg
    service:
      main:
        integrations:
          metallb:
            enabled: true
            sharedKey: shared-ip-key
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
