apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kms
  namespace: kms
spec:
  interval: 15m
  chart:
    spec:
      chart: kms
      version: 20.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: kms
  values:
    TZ: Asia/Yekaterinburg
    service:
      main:
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
        sharedKey: shared-ip-key
