apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 17.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: mosquitto
  values:
    TZ: Asia/Yekaterinburg
    auth:
      enabled: true
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.mosquitto
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    persistence:
      configinc:
        volsync:
          - credentials: backup
            dest:
              enabled: true
            name: configinc
            src:
              enabled: true
            type: restic