apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 16.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: mosquitto
  values:
    TZ: Asia/Yekaterinburg
    auth:
      enabled: true
