apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: three-x
  namespace: three-x
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: three-x
  values:
    image:
      repository: ghcr.io/mhsanaei/3x-ui
      pullPolicy: IfNotPresent
      tag: latest
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: three-x-custom
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: 3x-ui.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: false
          traefik:
            allowCors: false
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
    service:
      main:
        enabled: true
        loadBalancerIP: ${TRAEFIK_IP}
        ports:
          http-proxy:
            enabled: true
            name: http-proxy
            port: 8888
            protocol: tcp
            targetPort: 8888
          main:
            enabled: true
            port: 2053
            protocol: http
            targetPort: 2053
          socks-tcp:
            enabled: true
            name: socks-tcp
            port: 1080
            protocol: tcp
            targetPort: 1080
          socks-udp:
            enabled: true
            name: socks-udp
            port: 1080
            protocol: udp
            targetPort: 1080
        # type: NodePort
    persistence:
      config:
        enabled: true
        mountPath: /etc/x-ui/
        readOnly: false
        size: 128Gi
        type: pvc
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                XRAY_VMESS_AEAD_FORCED: "false"
              probes:
                liveness:
                  enabled: true
                  path: /
                  type: tcp
                readiness:
                  enabled: true
                  path: /
                  type: tcp
                startup:
                  enabled: true
                  path: /
                  type: tcp
        replicas: 1
        type: Deployment
