# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 23.0.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: qbittorrent
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.qbittorrent
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: qbit.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Arrrelated
    persistence:
      config:
        volsync:
          - credentials: backup
            name: vsync
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        mountPath: /content/torrents
        path: /mnt/wide-one/media/torrents
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
      dist:
        enabled: true
        mountPath: /dist
        path: /mnt/wide-one/dist
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
      books:
        enabled: true
        mountPath: /books
        path: /mnt/big-one/books
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
      flibusta-archive:
        enabled: true
        mountPath: /flibusta-archive
        path: /mnt/big-one/flibusta-archive
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
      #SMB-accessible for special cases
      mediashare:
        enabled: true
        mountPath: /mediashare
        path: /mnt/wide-one/mediashare
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
    service:
      torrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${EXTRA_LB_IP}
        integrations:
          metallb:
            enabled: true
            sharedKey: shared-ip-key
        ports:
          torrent:
            # enabled: true
            port: 28852
            # nodePort: 28852
            # protocol: tcp
          # torrentudp:
            # port: "{{ .Values.service.torrent.ports.torrent.port }}"
            # protocol: udp
            # nodePort: 28852
