apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - librespeed/ks.yaml
  - openspeedtest/ks.yaml
  - filebrowser/ks.yaml
  - media
  - cloudflared/ks.yaml
  - flaresolverr/ks.yaml
  - homepage/ks.yaml
  - huginn-extr/ks.yaml
  - jackett/ks.yaml
  - jackett-lidarr/ks.yaml
  - kms/ks.yaml
  - metube/ks.yaml
  - node-red/ks.yaml
  - organizr/ks.yaml
  - portainer-extr/ks.yaml
  - prowlarr/ks.yaml
  - three-x/ks.yaml
  - apache-webdav/ks.yaml
  - immich/ks.yaml
  - czkawka/ks.yaml
  - syncthing/ks.yaml
  - satisfactory/ks.yaml
  - dumbassets/ks.yaml
  - home-assistant/ks.yaml
  - wyoming-whisper-gpu/ks.yaml
  - mosquitto/ks.yaml
  # - zigbee2mqtt/ks.yaml
  - browserless-chrome/ks.yaml
  - pgadmin/ks.yaml
