# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: czkawka
  namespace: czkawka
spec:
  interval: 15m
  chart:
    spec:
      chart: czkawka
      version: 13.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: czkawka
  values:
    TZ: Asia/Yekaterinburg
    czkawka:
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 900
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: czkawka.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              enabled: false
    persistence:
      legacy-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo-archive/legacy-library
        mountPath: /mnt/legacy-library
        server: ${NFS_SERVER}
      older-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo/originals
        mountPath: /mnt/older-library
        server: ${NFS_SERVER}
      immich-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/immich-photos
        mountPath: /mnt/immich-library
        server: ${NFS_SERVER}
