apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  interval: 15m
  chart:
    spec:
      chart: flaresolverr
      version: 16.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: flaresolverr
  values:
    TZ: Asia/Yekaterinburg
