# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dumbassets
  namespace: dumbassets
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:
      repository: dumbwareio/dumbassets
      pullPolicy: IfNotPresent
      tag: 1.0.11
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.dumbassets
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
      backup-assets:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.dumbassets.assets
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-assets
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: dumbassets.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: DumbAssets
            group: Automation
            widget:
              enabled: false
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 3000
            protocol: http
            targetPort: 3000
    persistence:
      config:
        enabled: true
        mountPath: /app/data/
        readOnly: false
        size: 128Gi
        type: pvc
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      assets:
        enabled: true
        mountPath: /app/public/assets/
        readOnly: false
        size: 128Gi
        type: pvc
        volsync:
          - credentials: backup-assets
            name: backup-assets
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
    podOptions:
      hostUsers: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DUMBASSETS_PIN: ${DUMBASSETS_PIN}
                BASE_URL: https://dumbassets.${LOCAL_DOMAIN}
                APPRISE_URL: ${DUMBASSETS_APPRISE_URL}
              probes:
                liveness:
                  enabled: true
                  path: /
                  type: tcp
                readiness:
                  enabled: true
                  path: /
                  type: tcp
                startup:
                  enabled: true
                  path: /
                  type: tcp
        replicas: 1
        type: Deployment
