apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 19.1.11
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: jellyfin
  values:
    TZ: Asia/Yekaterinburg
    autodiscovery:
      enabled: false
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: jellyfin
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: jf.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          - host: jf.***REMOVED***
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            description: ""
            enabled: true
            group: Media
            icon: ""
            name: "Jellyfin"
            widget:
              custom:
                key: 0cde7ffa756c4e66ab54fed3f5e9679b
              enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: cloud-only
                namespace: traefik
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup-config
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        mountPath: /content/media
        path: /mnt/big-one/media/media
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
    resources:
      limits:
        cpu: 8000m
        # nvidia.com/gpu: 1
    updated: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                http_proxy: ${HTTP_PROXY}
                https_proxy: ${HTTP_PROXY}
