---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  interval: 15m
  chart:
    spec:
      chart: filebrowser
      version: 12.17.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      data:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /mnt/wide-one/media
    ingress:
      main:
        ingressClassName: internal
        enabled: true
        integrations:
          certManager:
            enabled: true
            certificateIssuer: fiveoseven
          homepage:
            enabled: true
            group: Arrrelated
            widget:
              enabled: false
        hosts:
          - host: files.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
