apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:bEP/AlTHkTBPQP96MK3WROj+VU6N0NxaJxyb/g+K1eJeM0vSal6gL4CL1pi+I9RPuVBvwcaIrnetEF4gtXcQwSo=,iv:P0iobqYk/NlVhv4sz4iDbEUJczZYdr00Cc9i2y4HkMA=,tag:U1M8dE+HF4aGhTuRMe7Rlw==,type:comment]
    #ENC[AES256_GCM,data:CgravPdfCDhrx7llxawbBRj4kuDqBuicVWlN+ujst0awetMGFArxj4WzBgg=,iv:eBcIdKdSSpGgGQTWIuTHsgGit1vJyYTl6hi6k+MD2TI=,tag:lYhNRQuC+pz9OJshd6Et6A==,type:comment]
    VIP: ENC[AES256_GCM,data:d70wJXNrX/sDkxa6rvXH,iv:3Wa6cQAZMsAX7yEYJlCVjkCVGK4JoVmo/pq+Om7kPvQ=,tag:TpWyTcP7p49YPXaRDuYBTQ==,type:str]
    #ENC[AES256_GCM,data:EJ2YQqTKgpOFb+r2DkHc2bHVfM/ThYfmcDM=,iv:J0fwpKlEAPsaRVzz/AqU2zEPanrs2sdxjyCVYHjZf2k=,tag:XQ/K1lyUjfvvpj2+LdRXsA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:dB20XLts4UJZzRNMqr2R,iv:EbGdf77ZCa6IrDxztNZu/S8yKT7dkOvZCbQ3ATWByjU=,tag:/gWeKmIrqLCkiNtgyEmmew==,type:str]
    #ENC[AES256_GCM,data:x9SJ3MvFIfUq7RHLeuD1HZbI2rOnA/jATzrHWuBEq/PBSA==,iv:nngrrJ4JmKsmPn3C4XrwSnpH1uCSf7xAEo7UF+m4J5o=,tag:u0Y4v1BYLdFGMoxsosCuYQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:eERBQ1JruhntpAZt/A==,iv:Cg2bM8Tv7yyc7OFlPT3QiLdExXMM1j9uXBT07pPc1cw=,tag:a8L2AWx6/LlNclQjPXQFvQ==,type:str]
    #ENC[AES256_GCM,data:B4K3IWief2qnt/sbBlOfp5QKkKsJVgg2jqhuU7/3N6YXwvpcgyr7ds4yDkeuJE8=,iv:chGAuKGDNk/leTk+LeIFlKUTanLLtomiLE9cb+gHifM=,tag:bgrAAYr4oBhRZ1lU5KJ/3w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:t3yMU34KyITObjoZvhJT9TNohRKSJmMIG44D+Z3iIQ==,iv:cdPdc+Qu9WAJbz+S7Wcb4XoFknOhHuFU7iMk/Am74T4=,tag:C0CcdzkiyZ7jy5nsPAl/4Q==,type:str]
    #ENC[AES256_GCM,data:ac2wiKYCeA27g/lETD8C0v9HePjJHJd5b5RmB/DHzPJDIQT4c26AkjNTR679vw38Xiau/m3Fs9Oe1gaLbyMz6nTrWkMJm0G2rJbVoNF5eBU=,iv:pcF/mzrUdVFjgNyeGHL3Qe7lG/9x3zuQKQphmIs6mok=,tag:J5IWWTLzdn2oNzzwFD+D7g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:UNpWITAXMfNIBjMakdBj,iv:o2zpnnnqg0kjyfRHShCuvyDEsrOJYGQD7EEwMGtGe+w=,tag:9khL7st2Um/SIUHvVJUHCg==,type:str]
    #ENC[AES256_GCM,data:eWTksYvnKk5822Gmr9XCFlm0E37wclFBS0dzJPbatEn3+ugB0eT3uzg2XRQVkLIflrjmFWkSEl0=,iv:sB+niIUvXep4nAp6NikoSSy/fvgN3ZCMFJjiMCGMD0s=,tag:glYs/u/NfCz6CQJ/zdatNQ==,type:comment]
    #ENC[AES256_GCM,data:ps2Sk06yux1dow514xb/0MiNJ3U0q7tptQ==,iv:bruN3iJx1f00aTSiSGEa67K/HyDhXIjHCU0jzZ1idcs=,tag:W1ZVUbYzXeKttTv4KJw19Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:QBWw4UND3sjv3yNWUjTeiNYm7qGmCX4fNAw32NkXiTiJhCHEfY+HihqqNeuDyw==,iv:QPs5hXpWe1ptRXA1D5nRJZtkyHXIXtjIMzrPnRdYK8I=,tag:YfzP/KVSWP/4Otbd5OVhrw==,type:str]
    #ENC[AES256_GCM,data:8HspJE3Yx9Eh0TDxO46SmxRnZFxafmgPT0+ZZrVjv43ENdehSFWltD/MxmfPjUd3LQSyzqQCrn8f8ckSoiQRWOUaxpgvcQE=,iv:c3kP+xM0bkJNWHvdLj0vtt/8Ky/dvYq8SYjzzQVy8rM=,tag:6/S81DQmidJRy8H8gOejqQ==,type:comment]
    #ENC[AES256_GCM,data:yqvM46baGCGC0ym2gfLARxP+lKdGyK2+MQ+eewVARhpDUKA03r8+0OrK3loZLfewo514IaJL,iv:Qv0H2jNpcmCem0MV3hTHcQcM3J4bDdVlR35g6XO/l7g=,tag:a1J02XrkyaKLCh6kbG8Oag==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:KurCnRI=,iv:ZptKmr4J4kcaLRC6jbVK7sXj9aNF3EgPQAMmMYfB5HI=,tag:mFXaI8w2ZVte9ZBBemmdQw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:4OS36eq/EYWevU7aW0JEBvgCXcZDVaLpiYMW8LurDVrTBf74,iv:ovOw1rOhDIUk8RepI7M5BdYBiDaGJTdvY0BufPAAOd8=,tag:gjcS15pfd2qtu5ONZFELmg==,type:str]
    #ENC[AES256_GCM,data:qgEGoJYasYZlDaYui2I=,iv:Gaaet7vSBWrnrghEmBci1jtNRUzXpmlVG98OZPW4HsE=,tag:JCpMSIkqp/OU8j4Ait57dA==,type:comment]
    PODNET: ENC[AES256_GCM,data:CqghjyqsK1pehTCPrw==,iv:iNojCgBIDuDgL2T5c30ljwgWmUc6xTstnPdcTo1l6MI=,tag:DJurPrCotwovDDyL8M4cvw==,type:str]
    SVCNET: ENC[AES256_GCM,data:9bHBY11M38WLuY11pg==,iv:8aW4/qo0FnyS84+BO+xiOsmA+9idN+mkSCcMvGJ48ZI=,tag:nhMAyTBc2x/+a91BhdTXWw==,type:str]
    #ENC[AES256_GCM,data:a/aDAJhamA==,iv:w9muCG0YeWwORXEiOOibx0Nq0e5IqzV+38zhv5QW6JU=,tag:MduCkMympr2JA7q4lIJvUg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:nO9ttjOhqOofxOnXWczT,iv:5bqCGyzZgOfZHoZIi2w2AmRA2UFPxPh41sezo7lOWOo=,tag:pE6g9IJ+QPdJ3Ea2+bx0nQ==,type:str]
    TRAEFIK_DB_IP: ENC[AES256_GCM,data:DmadYZfhIvXDs7p3i23y,iv:9zME0ZjMDxuZnjRSEna4f9tn0FSvATc3mm0IcEZGeyA=,tag:QiLnX2KyADagJzYg6JsAhw==,type:str]
    #ENC[AES256_GCM,data:mky0aNZbhQ==,iv:iSa4SDP0n9s3f+dFKjUJ1t1INXcDvLgfluTJ/I64oDY=,tag:q7MlXWkS288Q6QUsbc6Nxw==,type:comment]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:T78Srqt7b2A9HW6RH3sp2Q==,iv:JJOZxvpXhlhovGLGsDFeCoOw055qEacyYaFxfPKwatU=,tag:9RvophAPEIkAhFmbu2MUuA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:MXMjn1kmj74=,iv:OIrMJr9lPRphTqSPbjd5uCfC1WtGP5FTx8EpeOdDm7E=,tag:vp1TwMC9eSHoU6p6G5uBCw==,type:str]
    #ENC[AES256_GCM,data:EtnYT7daeY0rSztpvw==,iv:GZdyeeSDWXqkOvOFGWmC0Zz80515skSa4/7gJ2OfCEw=,tag:XQLHrSfRKxY/OKtgtSl3/A==,type:comment]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:vUSWRm5E7QdbCD67DgnLTG1Pd/umlAQ7JG0oUfK4ovSxbXCekcISRA==,iv:mSo8FEkUqesOFpvyK7xeri6pYvmjIGYOdpbHpPf+1ZM=,tag:wXYboKW+Eg2DE6kKnyt/Lg==,type:str]
    EMAIL: ENC[AES256_GCM,data:w9qLJXzDFvojNf9sNgsZXGVHEHmtgQ==,iv:1AVghQkDuNzvwnpiMZ61l7Nzl5L8e2mmgv43qi3OJ5s=,tag:ByA5SRWpo/20TPgfRaYp3g==,type:str]
    EXTRA_LB_IP: ENC[AES256_GCM,data:dSumqaDmaVWuoXwWGmtm,iv:EKgSv6UwfDffyVw1idn2ZiXg73llAB2sOVim/LVISXc=,tag:nwgohcOhrNcdvivUSsw8pg==,type:str]
    #ENC[AES256_GCM,data:wDhsJG8=,iv:sd8TsOAoT4hnX8yH4fHaInbxlhdkYhxgiZLmQaSud5k=,tag:v03I9CxcJpK8Vk4ozpyfdA==,type:comment]
    WEAVE_ADMIN_HASH: ENC[AES256_GCM,data:0ZHQl9cfEPjy49lnjzwGLCzeJN/GUEvoH3yIFnZXJYyuBqGSmvpHksD8pMIG0HcYLo9JIZZeoIdsQZEf,iv:lvK2oGAnlQkHIxadWPdEYQvFqU9qZAq0YKZxJaZI/tE=,tag:iMDlNC/N5tESHQGTW11cDA==,type:str]
    #ENC[AES256_GCM,data:8PP+Ka9btw==,iv:9RoqqcY63ERNcxPD80cKN52QdMHoqkqLcJVYf6YhDsE=,tag:GKXv5HmgyBLQQckhCR2NYA==,type:comment]
    VOLSYNC_ACCESS_KEY: ENC[AES256_GCM,data:TzJrPwxcYJeKNalARtZ16suvRtk=,iv:9h2Hp0MACp02PoxOjNUGhVJ29G/tc//dGhQmuXS1jbY=,tag:1Z2cDdUQTmaf+3WdxLwLKw==,type:str]
    VOLSYNC_SECRET_KEY: ENC[AES256_GCM,data:uaUMEyCXCRhDxs6ZDdaNC/82N6AFTDZLxsY7l2/KRu05bzI2g/yNmw==,iv:PqV6neFVUWilWOuksXPT/4xg8qaIoGD1wo2G26mwwtc=,tag:xkzniuC1fQC1C2HT322oBg==,type:str]
    #ENC[AES256_GCM,data:KTUJnwDsVVDnn7e9d7E=,iv:W8isZJPGuETZ6SYKq+96+QpW+RB/HdEbzz39lHWfOZk=,tag:UKjtghvqAFFB7fI+p+6Kaw==,type:comment]
    VOLSYNC_ENCR_KEY: ENC[AES256_GCM,data:IrSJglyTj697n//LhRjstQ==,iv:Owf811RCouvwdO6oL0+3+gEVoATw20WdyeImNJBxLHQ=,tag:IsMpR/dl9pNNiufVe6LPAg==,type:str]
    VOLSYNC_URL: ENC[AES256_GCM,data:qPX1YLOj2bRyHimoaBwNfQju+Z+0+0/KsT8=,iv:qLdRmsXtYangnAmeFXpogxLMtuIdy2IpFcjIqxBBWd8=,tag:490hF+1ocjdiIDaUuHHWkg==,type:str]
    #ENC[AES256_GCM,data:RKcfIUxOhQo=,iv:Sb4UBWfsVyVoZh0JglnPDXgQVSqWPQZw0+NOOwHy8Kg=,tag:UoMR7HBingBKYgnCQr6K2A==,type:comment]
    TRUENAS_IP: ENC[AES256_GCM,data:d862+my+RZibTzMSwQ==,iv:3cSgqMNOfDHdqYBihHtzba5D3WKVnLAaqWcE64M8amM=,tag:w/ptmYx/1CdrrXU/ji/uDw==,type:str]
    DOCKER_VM_IP: ENC[AES256_GCM,data:ZxUjq5rxJNyfYxqWV9Y=,iv:a5AZnCvRGBWQvto4DCU/1j59dcsrjaPxL0EoKdHKsIE=,tag:NYEU8Kf+iVtg7UpNDodE3g==,type:str]
    #ENC[AES256_GCM,data:jDBMSKJw6l1yCCE=,iv:jii551q7xifg9naIOv/L4AbU9P50sjn0s/KxeXX2X+k=,tag:baYBEVaC6OI26uf+ajLWKg==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:m0hsdb6gXrcPw7vJQBuDPw==,iv:NIAbaLayfkCk85rZ3Qm6D+9l2RICHNxYrefFQCYU8AU=,tag:icjwO9Bje9YZylmaWeQETw==,type:str]
    HTTP_PROXY: ENC[AES256_GCM,data:lPw5oLlwFSyPXpm6W05LYDOpjbHZvmIvovWtTD8lpFVHh0Ayt+aX9V/NauX5aN7E,iv:XwXf47RCe5+ySbNace/AptI9m1Agp6inK4EF8AYpsQU=,tag:7zCbI9l8TNjq9sGAtIz4cA==,type:str]
    #ENC[AES256_GCM,data:ALVeeiU7ZipT,iv:27/NuXSnSX2/PSV33Xs+KEnhDQz69l9CWu9Mdf7Q/YI=,tag:slj2MKp5LezmRsOOnfj9mw==,type:comment]
    ND_SPOTIFY_ID: ENC[AES256_GCM,data:gj3DqtyVRvzlNpFFXlph281OqpjAiu060JqytoS4lUk=,iv:CV5VF0+ovwu9NBNgRQ28XITFcvljSNwNVzVB7vdfOiE=,tag:rlaNzsjMzSLdgsgVmNblJw==,type:str]
    ND_SPOTIFY_SECRET: ENC[AES256_GCM,data:IPDP6w/sMYrIbcGF4s1LFN/4WhZD8LkE6a+s9gtly+A=,iv:cirMnI46zq/3xmV4ypoogPPRwYDUfAfe+3I0/zJWZYI=,tag:w9gm8LyYwoQIphdNaIwbcQ==,type:str]
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:3GrKdANZKHp8PGK+s2hvERWkmd1AAidK7RZq3PUxVNI=,iv:tlfBFwc1t6U+I204T1Znbm7AYv9G4wmqk6rXqfR0aVQ=,tag:0Qd48lMbLvIAmBZnN60Zng==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:igc73Aw2hBo0l4ySoizgukbVddmeunf0rW0JgO51sCc=,iv:eykBIjzjvdrga5hPDht04kQwKrjSTJ8Cq1r1ZNLHVxQ=,tag:6Bfd6oK0NEAtrp2hnuNWow==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:GB0uGQ==,iv:LCY9po6Lohu35sVk/eV9yOyfouhKeSsNbNxuhmJAmiY=,tag:suOJqC4XFJHY4mXht43bQw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0VPcm05QmZza1ZEYS9t
            QnZ0NjlUanFkUzNyNXVVWStMQkZTbk5jWEVvCi9hbDFRQVRRRFdVeUltUU1CUElG
            SThoMU0rWWxHejA4SUpqOEdRWmltUUEKLS0tIEtvYWsrVkUycWVwYStLdHBlS1Vk
            b0FMY044ZFJKdCtlSXJibzJLSUlrVUEKginxO0tOzh7aALvF67+J9uvkLf8PiQnV
            A7Vxjs2KzjwF6YkCJuytjufw5q0BgCx9M/qg8yDUpvurrEz1CJGxYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T21:46:41Z"
    mac: ENC[AES256_GCM,data:fUVk2J5Kt8EehI8W58PGRaPmfLe/QxXFObehRn/d7/XT0eHLZOqCeoYV1NPH2ZtjgD6mvC3EQDRqbsNj8TN94mEsfU0YIYWcic75X75nHMzTNBZTuV/XOKER5vaiGupJVScJumrQiUuDGcIAEtDdAKFX0XqghbzN12ADoN2uwUY=,iv:xyv71A+2GWbctLlnyL/6M64WRV9fRmVaYRkAZDoPOB8=,tag:NXfkE006sZy7WFiW6l3WZQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
