apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:j8Dmerdo4Cbh7cQumvdnrXuR4dzfKfcZPRHRBhJP18h0GHfjkM9s+P3fLNeYseZmL4dFATr3SdvOYAA1tWBbV7k=,iv:JBe0qqehrqIWsSYDVVARCzSLInDHKlPAlg72IsNkbEw=,tag:Huxjm/E39TCtxlmPqsY8sg==,type:comment]
    #ENC[AES256_GCM,data:AERaLUKX/tJDHLXnoqucCGFJd7sTTr9/DAdRqle9rLP1eFHhP9D6FMtlBq4=,iv:+L/X2oB1oD+YdCNUER6WXCSzCdVK3wBjLNrWLxQj384=,tag:YEM9qBZmDWYZ0cCDlSAZtg==,type:comment]
    VIP: ENC[AES256_GCM,data:7Z78pZIVJz/0R7JChSjo,iv:pIGoCQizkSQXgCCJsDYWuibJlSPKXPJQZrGeeFWTAvE=,tag:+mHu5bPGpUBbwSCTeMZJEQ==,type:str]
    #ENC[AES256_GCM,data:D+d5R/dGk2l3WlXrLtCNb7KGNR7mrLs447U=,iv:dGr9JWfpaPG1tm7CY+kQ4ajPgH3uQjBh/AzykXal580=,tag:RYy1YGTh04ZjHW4ABHqvcw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:m/6TvnNN2GozImd0jPG+,iv:rdXq1ATDuzUaRO6mqDATdbaiN/ijeSYAvEQynCwOpkg=,tag:XsWjxxdrkTsB1wFg4hgfGQ==,type:str]
    #ENC[AES256_GCM,data:IAlPj1A5iezOCOCuf9CkKLuLfJNMMXEaHWa7rWSRKkOwwQ==,iv:e2qxLep5KWRs3cOmCEvKjJzFbkhvcULiZdW0EUnU2N8=,tag:vsS3Kt6AR1ZbjDVbEMnhng==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5VO8O/oz5fojlRhuWQ==,iv:b0SDt3C8swG/bX2vmMwlaO1OHbVSm/Jt6OGCMW8q7N8=,tag:rKdpGHOL+wvmQCDQ6sMnuA==,type:str]
    #ENC[AES256_GCM,data:BKW9216mUllde2eWZggWnVR/e7t3AnArdXnprYGxrsuoo23iml2Fw76kapZ8MHE=,iv:/53/MxhWTmxrqlfxPI4FJf2HzkFqoRjRM15dgLzp+QA=,tag:vHxmUDm1B+BrLyKYntxgiw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:OsPxaUTyNjW72plvPHvqEXs3L8dY5N45oqZItPaXzw==,iv:sp4w4GYDF0PTexE4D87eYh7GEJGVsh/alUlntCKteEM=,tag:ZY6S4MDj8531GHXIs0GnCg==,type:str]
    #ENC[AES256_GCM,data:0wKhfWIWfo3YDW3XjBeE+v1/xRmIh2jYGEwg6yLeKB1NFgO5+DN+t4I6svsU4eVKaqhpV61V4aj4qkrhJ93xHIegEQfKkakHDdmChd2SR+I=,iv:6jM1tAWWColHfg3QKDJ2daAQUtywGELVZ8wPRs0R7pU=,tag:pozu295Kr2AQVGGh0jIwuA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:fzrjJUqH5RNU202I3Els,iv:P6lNpSN20FT2GLQ8Ozz/9VXXWSoKswXmIUi4eDD64S8=,tag:9/p/9kaxw+4280pMyX9VkQ==,type:str]
    #ENC[AES256_GCM,data:MRRkdyjzUSwGfB04rLrXHxPeF8keF/aeTJ+in7dIHNnyTJoBFMsUsBM5l7R9nsmO7brdaMpK88A=,iv:tYxEQbCJMh24ymNRvqHE135yoqTP9gpCF44du86J1ZQ=,tag:4M6PBClI5v1zzGKWJOns9Q==,type:comment]
    #ENC[AES256_GCM,data:8WqkX/zoZHPGsK0/TzlvoaKFYRb+YY3cAA==,iv:oEg+MuH/Hv+vg3/mwo/njQ62/JUXNnBGlWVXNS7jh+s=,tag:u/eqQ1dKPbWa0Rxhsj/gxA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:cc3Tg++UvDU3o5R7tP4PHuaYbb3sECtoB6PpRg6W8X+J5012CjPEmT9xM06A1w==,iv:MigeN5TaRIWOvMzB/LUc0jh0tjQnFNQyHOGqucGllWo=,tag:6vS+9qY5aY5AgRa9x0FCnA==,type:str]
    #ENC[AES256_GCM,data:qVynrsgJeNMqebXkRpSXpU46OlWtLIbBXcKGtOwld0vFPSu1aMnhDLLGYnneaVqYoZ2p7kLeBOCKzdv4Bww1zJuULfwwo10=,iv:yZXDOMM+2yfuxmgjWxRSlw1LrUQKg/3BekVvYXYiOE4=,tag:UcYUqD6SN8Q3j8RbeezxSw==,type:comment]
    #ENC[AES256_GCM,data:Iz+ZPbpm/lRgxoW2PCepPWHiJX0kc9ff9++s12Emfp5om0oLR7K/ecAqHzllWuyohoLMODig,iv:IoIZ3UWH73AbM/zqZ8dQNmmEBYuuJTszLrBOO6DO+xo=,tag:pWD7LJDV1vBgFgfBF59RHQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:84pNtvo=,iv:bs7ZzHn9LMj/x/Elxs2jTsgBq77z9fUcSbqZbLiSUQY=,tag:J+goNyas01hCA+a+kLWXlg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:AqB4AzzMkn21bAibMUICWrSQJsCSer2RysRJodSqKlcc7W9W,iv:mFIuscDkjPMn2bZln7nCo8s/7ugGdV82vRWCoQckFgc=,tag:oFzEwok8OS/pdAU5Lfp9Cg==,type:str]
    #ENC[AES256_GCM,data:oBsk60TVFAclk2T7SnE=,iv:313/KuExf6lj2vPQE2uBE+UimOKQQSHv66+K5vQE5Eo=,tag:4wJyk9RhDX6PsB/OzTftAA==,type:comment]
    PODNET: ENC[AES256_GCM,data:grVfP0DcWdejt6i32A==,iv:l60ZxAmOsngwTS573d5iMbsk4RbaGWLu/n4MSMRG9z0=,tag:XnYcRE1SE7qRWZA2MHXsnw==,type:str]
    SVCNET: ENC[AES256_GCM,data:G74OrmnQKnTbvV6AtA==,iv:ALR79aiaYMDFQuVH6qBp4QsKb0bp5luJFqWOJ+QNdWg=,tag:luexPAFjuwQ1XmQqysjS0w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:JWszLA==,iv:pzYjBN/ArtXzbbJAnKYI3SPGL/Z3GEUVSi7qi+KFgGc=,tag:BDAWIYWLUpbC4qh7W4w7Pw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU1BoZ3BBazVPMG5RVDZp
            SmdjWEJmekhWL0VsVXlVTkFyb1pZYXhNY0FnCmF4dDl1S0N0TzkvNHV2OXZLSGht
            L2pQTXhvV2I5dW5TV0VTcEdhbW1xUUkKLS0tIFc4L1l1MmN2VTRJbWxkRDRiaDc1
            YVpESEY3Y09qSjNvNVZEN2NKMTB2aXMKRARGvSsPVAHyznvHWJ3qWNan9dTUFpa1
            n/Ree/IDYSQXyjgfbHjtaYVYwQUT/TnQY+s+OzGuviLbVAxDk8hB7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T08:16:29Z"
    mac: ENC[AES256_GCM,data:gm4MeNbv/SmuukxzumlMoLQqqMzqvsfRWB9WJ3m6+uX8D5NbdjyU4RqLUVJ617bEdExld7xCE+rppjRD6mELY0AeQf/GqVgM0B9Ok6sNGUvT02zfb1PO7pcyWartv91pqBUFJ3Qo53JmXnw6Yc7sgUqBf6iIeUoQyH+Ba8k5N90=,iv:MuSwk4441FKtnvrCCaAez8aZTqdNvVt7TfLGiMWfOQ0=,tag:RnAtNZYo/a4NYOBfp2o92Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
