apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:j37lBD4HNn8bUAV0ZMysB0q5Y/jngVplQaj+SPrcBTPR82iCuFOjvMFkDURVww3nM5hhtNQeunVk19kpVSkPhLo=,iv:zrfHX8KeFGewzWf1EdShxz1NXuN3qVVHFga2FONQIxs=,tag:gkAQN0T0IAlXiYdqCHzcsA==,type:comment]
    #ENC[AES256_GCM,data:cXfBBd7nHZvvkc3pJA/eBUlY7Nsivbn9eixYd4sKMSe7R0UZNnveNRsff6s=,iv:dN7AvxmILknaBnnQx3TgNyrMMUSUXXVR3XluLu86QN8=,tag:wTUoizpYgubqjQnKy0BFbQ==,type:comment]
    VIP: ENC[AES256_GCM,data:Y7TOxM1JjEOmpXZNyfeT,iv:QixUXzzNwRoAeVRUwKOT3go/+GPVKg3GcJxkzjKLbmc=,tag:RonwsY6Qktq1g/BIm0ycog==,type:str]
    #ENC[AES256_GCM,data:PHNEV7e5REXPxEftoYYC8aqllexgY48JrfA=,iv:Mm52ar32YAR580sU3K3GPfgzSsnB2UIzjU/cr5a50p0=,tag:2+xMVdV9BVFQIuKMlbW0lw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:9NzGaiKMWvTfETnJ0gU8,iv:STF+Qh3xltmOs5GxyIWRKyRmFPBUPf1gUFe7rQcvbsQ=,tag:NWqNOvjU6l5o4kfXZiH3uA==,type:str]
    #ENC[AES256_GCM,data:ZhuPFWN2glTyIvvfc3HtwgI2Aw5oIGcUFfuFLIEZj9ibTw==,iv:LH4xSqJHi5wapY38BDBOyjWLuc9pjvzvx7Svi0fp/5w=,tag:g0WDL1fgaDU1LhRowhcHjw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:HpLDolWzokrHAXU3ag==,iv:1sIyGNgS7RkfVpt+7KDyECQqOg14JEQwEUMhjEIyIik=,tag:sJS3CYcv6yiG/SJv0IpGng==,type:str]
    #ENC[AES256_GCM,data:ddGRE1U94HTim4+uoQafzBfdPEh/7DMmjly+j8jx7wllCuBNlHEUa2AsZWtNbhc=,iv:44B0JqN6/Cy2r0IolrQvzxvaT3GvAGlvumCU5w5EvQg=,tag:cc8/et0dJcvtKp4Sm2vDqA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Zwe22XaXZiDWBtM3bXoVoXZIOvpeRQyW7l4MrLtfrg==,iv:CXR+yLxyZhoCcJiJzepit7D54DxsVQrkiCAaFa8QDo8=,tag:Dz9lwa3+iUjZtcQawQ4V8g==,type:str]
    #ENC[AES256_GCM,data:/JJjvrXbcMIy6e6WX3EMSby2D/gOXHWSWlIXg/Mqc7FhgQBdDegNJ7FbtnlCN/IsuFP3+AjQM77F25V7M9wG+GboJ6tlHqthsXNWomDz4wQ=,iv:wrIY0ML585dPHrzmD5YrbgkDd2VCEsTyI95QRptVIFQ=,tag:S6lc3idiwW5Abv/9BCAYpg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:DIQVxaoNHIawQW8ENzc/,iv:en717Vn3GmK3uPsCfQ6HdeUzEJfaEtCV7YsGZFP7f78=,tag:Z/1JxSimA663cik+lOkqcA==,type:str]
    #ENC[AES256_GCM,data:eb9sq/zm5liOiVBK/OzsFYRFzI5C/wTkwOoV7Gk10YyTcvzaZ6VNGDnqdL6QtfY0UpOV6aHR/es=,iv:zxdJZpunxkujo7Rl7uc+wAXk8VYnmmOober+J8VNcyM=,tag:VAWhgz9V1VdCF4TT0XJNvA==,type:comment]
    #ENC[AES256_GCM,data:drEcfTTVS2sJ8ccY6LKIG7kVzcGjr0IOrQ==,iv:QrQyKxujP3SW+bFpQC0z0oCXGWSzILb0kQVNkmfs1r0=,tag:vO5yjj2AjQjycyCH9nQriQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:6hahzQ7b7/nhGBRCx3FSUfGcWxwE0X2TsvWM7CZi3/LPYUXCy3pByvbRQGd+cQ==,iv:0PjBweEFGippCPYAkEoAGpHK1KIZuWJ6JVQNgyGEJ8Y=,tag:IPUbqjo9My8kGhRueUY1JQ==,type:str]
    #ENC[AES256_GCM,data:F7fq+NPyd3dSg4Cro7W8GDIuj+jMG/2L6CBxLye+ALdUcwtOYiKQEO2aN1kUxgatI0eKUXE5dtkpZ6HzhovJn9RXXU+fnI4=,iv:MVtrKnOwSjRqqYljTuD/p+8Uh/B2Civ7o4kV7X2rytc=,tag:ZQKo9Ov6hOjJTZM0f7ii8A==,type:comment]
    #ENC[AES256_GCM,data:cxm7JvV8StKC83aZ7ZdsimLfD0Bk5zgmag7I8ZGKuTlWlYSFYkai/bDJzro8XrmlciX08ZIi,iv:yVsyfnFchp7oaYVkrDhAIX/uN5J7jngRHBMFvQUz5RQ=,tag:+ntzGUODZF9+LCtm0ptk+w==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:j0bMMfA=,iv:Y0CjNiEJX/Ozxm+1LgLMm2TjAUtq4TkUX+iTtd+TUeg=,tag:/pDA+wvnrCHVXuwSEBgcYg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:o1n8E7TEaTBAL4VxDVKW/z2odkH/Sddqk7a0aaj4vKDSKKCR,iv:0QpdsAhmkAz2rB6WURGSQynhCURr7Dd9OK5mJtGBWMw=,tag:0yXRagGZqQxDe7ljnJ+DkA==,type:str]
    #ENC[AES256_GCM,data:1guiLuFgXNvrrDomOzU=,iv:dtAifC0g45XMO+iUxvZ7VHTsnFVgJQRIJdp2eQkVetE=,tag:NbV1UcXWwsPWmsNwE1802g==,type:comment]
    PODNET: ENC[AES256_GCM,data:kgdmrjLtsLAo+0FKRw==,iv:VFdDk2KvmhqnG73Kl8N/7D2WIrbH6kcQIzTwwUhVfYI=,tag:4aanVvk8XbqO8h4qOk3WRA==,type:str]
    SVCNET: ENC[AES256_GCM,data:rOt7akQ5yhpUQI8JaA==,iv:YqiHOYXzNw8BP68DCIdplZiIvLYfs7IO2OzhrEqhUro=,tag:u3tQlzFsfmwXL820DJUNzQ==,type:str]
    #ENC[AES256_GCM,data:jiMGMb7Vzg==,iv:1Q+eDFpRb3NzmCrBWnqKZiI5moRQ7efCtm7qbWBVY54=,tag:c7H44g0MckWKejZX0SNWaQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:WRYg2Zez7AkTkLzQdU+w,iv:wM+yVeztsF1hP1UBiZUrXdgu41j2bpM0Rv414/eoMFw=,tag:SxWwTznNMpcsqDEJ9/3KCg==,type:str]
    TRAEFIK_DB_IP: ENC[AES256_GCM,data:5nNk4QxfNAwYGU2HLnBs,iv:fZeTbw9wDYLAvMeE+mB+C90ek99mCqqr4x4bE59/eE8=,tag:c/qsG9uJcMFBm3fv0+szJQ==,type:str]
    #ENC[AES256_GCM,data:udu7QMZHGQ==,iv:khyNwfHoy1IZwTf5ROr0OOaQMfk8T9LGItK/MNdp3y4=,tag:RY6uSTgyMQQEOUdN0pAv6w==,type:comment]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:3AQUiAUbqMlvnMC0tTJWVQ==,iv:i61HO9WvEt446KiyMkB+J/8juOOCdGnY+Ffhuewrzls=,tag:DGA5znZuzOWPi/FNn6KKfA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:BW1bPtJJy/k=,iv:C8Zf59BFPT3BAbnJ7hthezi4ZRtOWdD/WrguhL59VPM=,tag:FoCbuoeqCpQbwNGWfxuOXA==,type:str]
    #ENC[AES256_GCM,data:q8G90pHU7l72xE/NzA==,iv:L/AxrIjg+mtJQIsb1xfHWdTPimcZ94S85xpeEpr4DWE=,tag:aNdva8mjAXnZBY8ZTT+pMw==,type:comment]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:AfaS6PVY0y8MvawOvhRbo7x5lznzVQRKXJn/Raf1m9S2V5XMvGWGVA==,iv:5i89Y8tMO7oofL024agjIchG/l/lT8yOkXa2EIFy2KQ=,tag:lkoTgAgwb3X5i0nLFRLl9A==,type:str]
    EMAIL: ENC[AES256_GCM,data:b+LQ/9QIh2JprMjeHIohWvAqkUidnA==,iv:kO7kFovGqtdC55TFmQrEdJQmFfRrBIz6X1R/Ov0pIOA=,tag:iGC++a4SZ6Frc+eZFJKe/w==,type:str]
    EXTRA_LB_IP: ENC[AES256_GCM,data:zVQcRE7FnLQ1NeFIdAo1,iv:tasvuC+0ckkvr1hfMtSUQI4iF+DhfCdH51bMb5leKnU=,tag:syHDxwiJxs1wNY89Gf4IVw==,type:str]
    #ENC[AES256_GCM,data:XS2dH3s=,iv:7q94rNzk3euSo9qw/fugz9c1a+qd84jtsHUxN1KP24w=,tag:L4E/aD/Hc3rUTLyqS5mGIQ==,type:comment]
    WEAVE_ADMIN_HASH: ENC[AES256_GCM,data:eq8cwUYWcgddZDrJFtoFo0T7dEfFXAmV+ByPfcdu/HOnAu3+p8JtXW4WOqazeOlO4nvwZBU4FPK37Loi,iv:Hp83pDzb2VQha/CJhtUV3ei9P+4XffgTT3vJo6DoKo4=,tag:2koIYyOUlN0P8dP2rnNxYw==,type:str]
    #ENC[AES256_GCM,data:DIIn1njTxg==,iv:CHE4bBLkL669NYjGg1AkHqT+xsPE4rOUIWrJ0EDLgQQ=,tag:HfGoX+MXsynye47AID5crA==,type:comment]
    VOLSYNC_ACCESS_KEY: ENC[AES256_GCM,data:RuyM2KRz80IvO0BY+C2DNA9ETkk=,iv:Ge0UsvgRdtQJc5fxbWGAFZfSYxRQlJWXBempMC8GRtM=,tag:LOJ5Bb2TbeV5dj2yrWy3oQ==,type:str]
    VOLSYNC_SECRET_KEY: ENC[AES256_GCM,data:E7VHN3n0G2hTH7M8Qa4+Lk34RNREdpJgR+Jqe8RXCn5ZOCdM5BWmsw==,iv:75XYN0aZwin1FaEw56bNJ/mz4Hs9m4vusB3m7+JkGoM=,tag:CW3etZrXYarMac2g+hV2wg==,type:str]
    #ENC[AES256_GCM,data:nCSE+U8=,iv:OQhquBBGN7EqKOtRz6QhbSfpxqeqbTKRgnUBxTpz7tU=,tag:ueXXwXdeVCN1rmcmyg1+yA==,type:comment]
    VOLSYNC_ENCR_KEY: ENC[AES256_GCM,data:jnrN3kVMNF4QfB5dQkL14ylH5nhcLbEdKs7WjO0KnPyPrdYa8TK+aSDc3w46hIOz,iv:mKKVHc3HNBecAaHGTUNNUySm5wuqEHa4msJj0guBsW8=,tag:po1hL+wph8Nhq9WWhutrYQ==,type:str]
    VOLSYNC_URL: ENC[AES256_GCM,data:/tKzDSfO1Ddn5XzZ+6gnNCHoEBMFnQ4VeuA=,iv:3QrUw39Wef+FPPSO54+nP5W/ZAScNuqY36i3vONQZ0s=,tag:PnO8a4Mw5lyFRK+R8BNUeA==,type:str]
    #ENC[AES256_GCM,data:k2lfL/Yssio=,iv:xNsmuJ4Wz0GRWgvgH4QdAQCJU+Jtrqn0MnVWWKjHY5s=,tag:SJpEQC/CoVyH3Mh1Gjem/g==,type:comment]
    TRUENAS_IP: ENC[AES256_GCM,data:7vuA9JxaKhKZj6UAmA==,iv:3JLtQlqOsFl9JHnIW2DDOLJV0a4/DXmtcbpVAbBaPxA=,tag:l8XCgX5TD0cxhKhHiK0MiQ==,type:str]
    DOCKER_VM_IP: ENC[AES256_GCM,data:PqfhgUm5pAVb1kXkImU=,iv:3a8vIZb7hznR1WABEwQSU2pun3sEsJB9H89FvKFrSmE=,tag:ByjTFSdON6nTRaRHtTFwgw==,type:str]
    #ENC[AES256_GCM,data:OQ2G+k6jHuneBy4=,iv:pzjK57NUUA7flTBeBux1XmtIVOISohW0MsAAXmiBF/k=,tag:8O87YmYoIEQ1OB5Nu8NKbA==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:/Lf1o5Nq8cAb43bHsVWIYA==,iv:eZU1wJCJf6xQN38aOS+66RF5U2aeX8LX0aEF1u8mnrQ=,tag:RPlbPQhvI9ds93UrP+4B4g==,type:str]
    HTTP_PROXY: ENC[AES256_GCM,data:ZVnkGpecZMiu5YQpfXRvNFvyq4N5Fk6CdwC8GyU5NI/q5950I4BCFc9ZKo170Uvr,iv:lhrSanFMuMsUYOfa67is5BGnd2Nfut1ShlniNg93WL0=,tag:GdomCv+HEGeEj6rH9+qpAA==,type:str]
    #ENC[AES256_GCM,data:jEhNGYTdgHdF,iv:YjwlsRzTmwhrTXwRNZklaXVNLNMcTu5G8c7dXt8EoAE=,tag:XAPu0Gi6wiOiLdsevJaTZg==,type:comment]
    ND_SPOTIFY_ID: ENC[AES256_GCM,data:dYG1oe2h2OSXS+Tjx+1ZVXUVPsVU4COZiP7m2wv/k6U=,iv:EZ5SU6tSEABkG34UgSQX63iBWvL61NMSiEpYBC/5gkk=,tag:ujatZ8x3eCo+bVcIOy/7NA==,type:str]
    ND_SPOTIFY_SECRET: ENC[AES256_GCM,data:U0Tcr7pexFJIuLrMdt3T5om3/M2J7nSYPd3Uq0pbndA=,iv:V6miIfGRTeyuwR2yS8ZZ4wHpI9L0DwVQFCeFs4EBg6k=,tag:Inun81Y35Fetu69gvjLgiQ==,type:str]
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:MTrnyA33Vuq8uqnsnnBhFhgqfMjpZ684dECsD6P9yQk=,iv:mS6CWikHWd1lk0j3vwGoAEIzK9lbvptYExAStyvS7xA=,tag:TaEIkDv87efDAdW7D3s2mw==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:dKPocX8NGRMEteSyD0THrOE3gW0LJbYSzrTcQmAgLUc=,iv:1LvwBbgGVDCrO0bE3DXEZQZ/eN8LJ8MiXEVNPE1h5GY=,tag:CG7o+xtBKsU7NIpJMUf2Qg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:djcvqw==,iv:lhFSnIV8z59JFhp61E5RbF1Ztl7lZjzmW2IA/lMpSCA=,tag:fTipq0UoTvkKSo5a04wNsA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QlZwZmxTYjI2ZGVyb1V4
            Mjc0ZlBsZlZUY2ZnUG1vYllJeldiYVpDTVY0ClBvczJNYmF1dGh5aFFSM1FObHpD
            cmZHZlpBeW9QQWFqN1hCckdsTkFmSWcKLS0tIDFkaitGUUEwNkRYVjV5WlpvSG5Y
            WVZDaEt5Mm1IVE5yMjBNTUx5SzRqTVUKShIELQVbtuiWswYErPLPCQIOU+Oe1QGh
            cYjWGQ2rJ9nR7OURO3pw65/9MGicmRjzdN6AjpxfHQN7xT9v76jp0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T06:41:24Z"
    mac: ENC[AES256_GCM,data:HurlsVLXpjGZJQrQjV1t4gg+8da9sCjDkaopfVkSbtU38YmPOSReF3yNlbBDlVNrIFHgeNJ2v4R0XBO4B8BV+bZkb675N1d1aMWhhYZCSJ6uq9DiiFNqURFQ5fg3zJ2ympUvTFafq6FhUbjRp6+fxb+tzJwW5xCBZK3DAQYVZrk=,iv:AlUvDhP4j/QIV3AaYg9yMYHJ+oZjH3Sl1YTXNKKqjBE=,tag:BIPCdZXPSKVGGVfMSTi6wA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
