apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:KlaRJGAXFXS/Cz38mOaHY4Pxn4nqh8G49vzdSjkuTwilVkyvF3GIDBlpCB9CuY516fPqd9+iSuBhJtANBapQdnY=,iv:jOn8VCBjVPGlmlKTXpyFXCQVJBWdgF7ywdXl10o3V+U=,tag:TQ2jfynZVg5nWSGcURfi8g==,type:comment]
    #ENC[AES256_GCM,data:O0aPVzkLsRRuSJfhYTdwZlnhu9V/2Dr9DXdRO0UozA8rnMpvktsZhaoa6BA=,iv:4cxCm5cLDSRUAv7E7rIfjZEOfXrWyzHzAjBwEiiyBss=,tag:qQjt+Jmt2oEPN05hVYiw6g==,type:comment]
    VIP: ENC[AES256_GCM,data:XZ+gGW8dea7hOhLo1ID6,iv:E9OAidyGkRzTjSP1EmfbQrZ1Rh6QVFr0XudLnYTHe6E=,tag:i4AwKwPLAB4A5kbLlgM0fg==,type:str]
    #ENC[AES256_GCM,data:chL1Bs7hM4d88/4IJoU70jMKvKyOW/GLBjM=,iv:XlFIU9yYnezo2dANyMKVuuHEsHyYPQ3tKXD5VOq9GC4=,tag:zcxjLNGNPHe2q3AjyqLukg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:cetuByxITOzcZ0NgNTf3,iv:msx/h75rP961efa04y0zu/taaUGt/cKpjpZPSwhD35w=,tag:mgpQA6cEnvO29uAwZ3SBzg==,type:str]
    #ENC[AES256_GCM,data:2V0SnfsviBw2wqPS6pYqYCOwVseIka2lrOE3EwNdeaUBXQ==,iv:ZShbknf6VyhQjL4N+wWZXlnOKQu1ArZZEgJmWuNIFO0=,tag:w+fW60rp7TClcJ7MGAdBCg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:2/p9+YbU4XxfXVo/hA==,iv:jZR17u/Hyux8RKy4qhU8BwkhKAr/jVyUcOWaWnafBWE=,tag:R/vUGLeyyIZG26WWkNI12Q==,type:str]
    #ENC[AES256_GCM,data:MYE5m0QLu2Klhq3ysBTHXaQO8lqkojepa3zY8k+i1i+AG3OxO5bhEQXOrki9zSE=,iv:aECWSadHRaBXqIIINP+uKz0qA6eVZzfp2GlAc0q/pbM=,tag:lMasyFu4CFMlYVhq3gtHwQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/Drfj7xy8EaPyprzV7S/SAzHD+x7Pgu/8wYavCLELA==,iv:XcdlPsZXX5qsBSVq5oie4pG5KOYJWjxpnNP1YC3vTLQ=,tag:ttR6clEpiD6fiZI/q10tmg==,type:str]
    #ENC[AES256_GCM,data:tJU8lyA2XG6l4ZDwRA9xmsoR0DuWPe/N7It/YUMcjmjEV2ogZpmN+El9opM8fVmsDLOZPmUGocfT3QGt3Om0uuqOSAFDvfVI5OvuHtjR1NQ=,iv:ylKPzGOWxO8PyLzRdFPNQHY39wEP5qeymMXVN0+MJcc=,tag:KW6GfBveetxxm57vV77Vng==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:WKG0i408EqnhCdHqVtYt,iv:EdPxwNtZTQJUzx27Qxe4M8aIKnoL9wt+yy5rly+dU7g=,tag:1iv79lxBs2nuf9BJsZlDjQ==,type:str]
    #ENC[AES256_GCM,data:KDEMCncnCDf/TBNeBGlmZy7LPq+tB1nYqy8SDsklU+PjCm6f2zAnbqtjvHn4G8wGt34tG/fXVz8=,iv:lRiKP1ntGYO+oAcQ9jeL0MKxwvNWTbiIXQInrOolhs4=,tag:cRcbWVVSmS9ViYUcc++8Jw==,type:comment]
    #ENC[AES256_GCM,data:O0OiUUf6VuOi1I0i99/DJpVkAmvhsYAmbQ==,iv:M9dyj77xS23Og+zTWlsQ3b9gxJJWEQw9OjH6GfzYdWw=,tag:Wrxx3Cob0YtKJ04HB7ZWGA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:vpnK9og24oN/+2l5P7hnFS4STjh5YzH8Vh8tM3+jgF+FisA7moFacQEb4MWy/g==,iv:lrp4Jen1oEmHiBhG3Z/1J3uYwd1ZkceqR0/iVjxJrb4=,tag:S83XAdgs/KEMi4tYdsjylA==,type:str]
    #ENC[AES256_GCM,data:dZEBlDiIga4oF5/yMy88Og6LZ/a/OBXrTShUDZVS/U/ZkXrAJc//C2Gwr07+ohJU5oZmzlTuDaevbwFgEhVYw5bFgDprYCU=,iv:O89aR/vdmrS+LnrJ6CLTXrPkqSZbUpSv7sPhorvM3r4=,tag:t/8zwP0x/Jux6H/fpwT+Ow==,type:comment]
    #ENC[AES256_GCM,data:o33N7aBxrtjsf7k+7KQMFy6YP7F8xrUHmd0gnwyWPBll5uWObqEtPKkCRdX62PUv/+s9BI7a,iv:HYnVkY8HIykP9ejVvrOOnR4ZRP3hg2C10QA1GXomTeA=,tag:d6/rehUziAaXE+dsHtU4oA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:25s4Kfo=,iv:p8oUAlgRGzITJzd31NReyyZ5AyUqWYo46uGa81Ty3go=,tag:FffEr6CdjhbyKa0FiJ+h8g==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:fZJvwhZwTLQQqd26OCGVBlzCQpjBmRtetfo9rchNrU+qTu1O,iv:qbamtShCjEeeAPscipPGGuNrwp+5jYeOXap6t0uqVTw=,tag:5X0cZFbfFeqvYGjy0T5d2A==,type:str]
    #ENC[AES256_GCM,data:FtzVWKOt75aj1z8izfM=,iv:Np3cfZehg78K0Eqo57fklgt/IQaH8/gcRNbqJ3qiTTI=,tag:eE8SJwIju9DnrZXJASDtEg==,type:comment]
    PODNET: ENC[AES256_GCM,data:tjyEiBzFIzaLsoXRQQ==,iv:t2vWvxH4J7gqjcArQbw/tJ+w+sxuAANFTiHUhM04sqg=,tag:k8HAt6HbCXwiKSG8pOG6Xw==,type:str]
    SVCNET: ENC[AES256_GCM,data:W7hKq9BI4sZAkDD+fQ==,iv:vcCbIdEy9hRwF2Ydg665ivD7CiQU5dudbOls9nRWTno=,tag:XwVktpDz5ZmNTUjWkVSWNg==,type:str]
    #ENC[AES256_GCM,data:UdZq23AlPQ==,iv:vi/JseYB4jttJU0qPMotHxB0tCfzTHt9QMyYXE8IyOc=,tag:TJ9E03onhdFIMWjbTJw8aw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:NJ+6jlhPRvAJ0f/MMsJ4,iv:/TICW92E8+ixo52HcEWFGKAa2Ov9+kwOVsabH64xANQ=,tag:6+YIvDKmWjaVPPSEwtL3WA==,type:str]
    TRAEFIK_DB_IP: ENC[AES256_GCM,data:GrT8Q5Xm5LSB+tB7XBe3,iv:ytBJvFObC/Z4lIPNdHTMdbhfEJD+fbJurYrd9Sjq7lk=,tag:aE5hd+RYoktEog4wQII/LA==,type:str]
    #ENC[AES256_GCM,data:/dccMHzeCA==,iv:VxRWcdv6eq2s1MgTeQTjiv9//XXtuB2qb5KIn24VCBU=,tag:EPODHSAlHj99yxPdJ4hafQ==,type:comment]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:GyxIqYIuGKzdJuKmKAk=,iv:DQoNUM7GRSXn6m6bOsRlu021jXr3vZPC5SeMytslZfE=,tag:6VXgjT8fZGSnSHuriP/GAA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:/c+T01zIa/o=,iv:F0agaE1TRXm5C1P/1fiSNnFzIQylvtoBF9DpocfKqU4=,tag:OEf9FolGYWjVHZjD5rYxvg==,type:str]
    #ENC[AES256_GCM,data:XID0SStRrEXqMNFrYw==,iv:SBJo1nB7OeIkFg6qincIESs5tfXY5YaX4WJv2N1uH04=,tag:YBWXZwFGD2htjkwHbtnidQ==,type:comment]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:B6+eUOOmfxsd0BGKxpsZv9y2D6X1LddrISrOgbxXZIKSoGywQpD8lw==,iv:fODd9t1388PhcGvAPGmS9Iu7QfCkH57b/20aSlfnutc=,tag:GzNK6+NPfBuU86YSZYqiow==,type:str]
    EMAIL: ENC[AES256_GCM,data:x0ASjZeySIm2Gbg29ybdEmOgk3Jd9g==,iv:Qs/zXPUV5tKuE0Uz+1XqzR8JSS1KlwEWBOmlpMKKCbk=,tag:1BZUVLqT5KkIwAz9iFLGgQ==,type:str]
    EXTRA_LB_IP: ENC[AES256_GCM,data:2lymjHUuV4bWTiha5Xli,iv:VVJn6w5GaxjxDdO/kUOX0xV93EtGek4qREm1L2PhGc0=,tag:wlZRoXbTXYkDGMoGSSWv5w==,type:str]
    #ENC[AES256_GCM,data:Sz4zbmA=,iv:/CjvbDWorwyVCTZ4nhlxCLXikRq2D/LF6o1Tj/rUwe0=,tag:CojgSVEOJhgpbqRiHzsTcg==,type:comment]
    WEAVE_ADMIN_HASH: ENC[AES256_GCM,data:cN2Bgx8odckGzjWhLrDO9dapEgybHkPzLXaw/j++xY2f6WfRNWTjbsPyc2o9UPMI0emF26CoRuYGoWxc,iv:HVn9fAUOZZ5o+zI3Fvs5AQ0IJqd1nN67RE0tp989Evw=,tag:XmfrZ/4laRfpa/mAIXxKBQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:zNd6SQ==,iv:soQjAZjM+ulye/Fsw7IuUIG9mD2PcY88GU1t5/UcUtc=,tag:XmUNFjzg1tVlr1QFu3avIg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVll0a1o2RkYrd3JyTTJZ
            b3UxRWVjZXBaREVBZzZYZEY2RXZYaERVRVEwCjM2eS8yVm5zRUR0ZEJKZjE3VGdV
            U01DbTNXRTd5RVVTNllqb0l0aU4xRncKLS0tIHJMYi82WnFhRVFBdU1zdnVwZUFE
            allPN3l2NDdmVEFBWU4xVDJKS0hFL2sKLCuii1qSvf2wCeckoQo3b2bkFjbcoU6h
            jdqs7IBWK3Jfio8iRHTo7aFfzeqEHhVDJnYifzioEG+o1IJeU2Hslg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T12:44:34Z"
    mac: ENC[AES256_GCM,data:6X0IwfMraecILNWUO3Rror8ShH+9SydKZ5pi3YLcCV//Rh07xT1nujvZIdja+pAJ0p1tIkGWrtOsTKYbhkv11c747rB7bF69xtO7Y2mERt4bFIpLDh7isM74C6Ea0h4r02a06zaqEl1IR0XWkOxBThaOTPHsJc98GSULlE5wqPw=,iv:wH/P03a0GWFLB0qV7OM3Kwd98HgAgwGlcsngILHVF/c=,tag:12AR0KbGYCw9Tv6NQtLwTg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
