apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZQbpnLtpttHoEcA2KZp/MSnj0rMKS+fieUxBOidA9T8bajRkdsJ/6jTlcM0Dd9VGs+5mn6H8ooRHSgD7ga4QSt2ZruWipWrH6Skyz8PYkE62U4rWn2P8Z6nHO/nJrqSvxPBjSAVvW6czehPele/w/ENKIZs71AeMuMYCqr8f7wTRIjwyWn3UEv33Db7WMk5Qj6wp3/JcuvPL40IXkcdYuS9yIyhX3PLLuPJ4Xw8ufey8JT69BmEXUuYKYo+0ROEarnsFCFJKtsuFRvuqZmPnDyOS7NWxGY2M8uFadeNuf16kiAgx6QEf21pnM2zozqQlL1WmR09I/0owo8Jg1VVYkKOK7AAtG2DrsDpaogFprYtw20EYag0i10MROtBpEwM0,iv:Qzv64timfcTP3nbeRFB+XFTycAeWOzOvS+lD67kqOAg=,tag:iGy+XKibGm/PKUa5/8lcIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:FL0OzPY/WCfo1spKWvPRYUdiPYerNiFVvP1MO/+LJzW/LK4fdiKANhP+KMlz9UFYK9RlC04FQhG6uQi+ZwRsu+35SD5lorE8sSWdZAE7dvtwXlGD2OxkdsrJL969wMS5K31HzwcPBOOsknK296qiONVOgSVRHFB21zQ4RrIP6CSDjljqZCKTsHAmZJPzl0WasgRcwdc2+zRcV5QAlLH/xNOC+1zcPDGLdkPnLpzDY/x0n83EIWJ3TxN8sfxIdVWDG0CwsRZyChYI2w3/YQ==,iv:AWdZBWIiD/K42ZATP8r8cf8XW05ExXkkxajFosWlSOc=,tag:vTUjF+prtwKH6JH9wuhFcA==,type:str]
    known_hosts: ENC[AES256_GCM,data:foM4hVLD66ezt9jO6kwt0tXgYGxcPE5PZ3XX2R8luqSoKig6FH5AGAxmpfSMs7drerHMOF9rbRengbupYdLyvReb2dDj+D6KYBBg2E0sb9NOoDA8pakdnnFklRvE4jU4x/wsSUxKMNkCEq6a2krrUn/lVyVfrqt+McbPDtjsvgNttpEwo9wzdLxEZNv8/1y5IW2za6AVwlzEhj5DUD6+vrleAE3POD1xUTwg,iv:RonVubwYcP32Yx9XyL7zpSP0TV3qUwdaMVdQZFrKcmY=,tag:2YsGWTnNV8+8c+paSeCVUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmenZ5RHIvV3BlYnVaTXZr
            bllUalVCazFOamJZNTZOOHNubmFmRlZZa2wwCmc3NWp1eEJhdy9KaE4vL1p0NkRM
            a2xDNWs4K1dLeHZrSzFxaWc2a1JwemcKLS0tIDl6VE9FdUpJMXVvbUoxYktHSThK
            bE95Q3R0N25nbGt1dnVoSXBVeHRJVm8KdTM8+BVRkbx+hwoCXEN+HSXMi+raLEUO
            EX/G83brRWyH5MXyXGhW0QlVAq+4jyc7soaY2hfFoAHurBI9g5Ckzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T16:54:44Z"
    mac: ENC[AES256_GCM,data:f8Vr2V+izJEUVwOsJmYQmnrlCp85+fniZc8sPJOt6B+AtFQQIe048CPd6TlmKGvQrg6FyfUw9AZ/JmgeZSWrRczQUFnqasQKdKOuXGxTXeWrWlM0hPGiNJw8YZKZkKmDPs4oPRWsCBFRcBWyzgIwjyX1ePK27Lp0hkTy8j++p8g=,iv:fYQphrWBfpAFejoFZ2u5ydHxdhozLbkrOTxTycTtkJo=,tag:LYeEapyCALRtmLlbAkx7VA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
