apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jE0gX8CNcIQAsnGgrEloWkoBu/OI/34roGTm/l57x6QqNgtlMvceOyA6k5bFgtsiZIU8oihkL0k2zDonOdWRgeJKZIbii1OvaZry+cCp3N4ffBWtT0cNm5hhnuL+UIqzCgKDAaB7opfrjtyeRytlWlezm7xYXibpE+sMEu4xvIf1c8KyU48fT2/8tnycK1YD17ZBnihD05UUsuTfhl5HOyLgSGk7NkRozb+p7hV/2gD5XlxjShIyMBuM7c/V7HgOAoZ/5t1sSUhaSAMYyAvh+h9m21dOBvSsrT2gA3NUuWYBxaDUnemO43kIxTzibPF3H0TYaVTpEU2RqbNCd7xvFB4s/tnlsVhaJsfmHyEHj3bTCz+XrkhD/Wov+VW1tm/E,iv:SlqvMUFpx/czvUvZZK7RZmU/3/FPEK8/g5Ey3mRYlO4=,tag:A1G4vsYn78ga0sXnqd/IrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JTVKaklhXanEBu760KouSfzswOQZnDhxmBHGK49Xa/LQOYFFN1qiJr/hWUUErBvjAVc8o7yOhXUMbRz2VZg0U5/fwYqiuf+Jq5iF+0YGzzMu/eRKuWzKuoDkJCuloS8dAgt5CHAtlPPKl7s3ySYT+2Ci/hpn1xRyShymUPI0JEDfcjAauICLSaqpsTE80o4hlWanNRE6feyeAwOyN1KOF4tinpEgZjC/7aK/FNR4RwibWPfH32kKR1l7K0vgELqRZT9TXdJeL4nhyEpTXQ==,iv:xaq7PzdoTodHF/4ShBNwR8Nqjaf1INqAnDZNlWUVJcU=,tag:cuZtwhhn1ZkjhvQoFsGM4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:8D2ghdGgSRVidqwyT+jmrW2kOaWUnKEghjkKeYTlENe8ap0gsaJxEetMYc2wP6ctnJliYwmzhRLYHPVVQ0lqP1/BsBCtprY+VOZYQWutuMkoSoXVTCPY1LHdKnz4eKDCbxx6fv/jW2VB3F7ZfFOZQo1wCIsa7NrUUh5BTV1OC5OYSOcu/1qYFQcPXL/M0FFUFc/oYXsAV2P+OrV5GPobpEo8B4FRtToGxuGi,iv:Mso0PVtftKHZMl8x2kl3JQpGURC788SpiDtH6vvfhEY=,tag:Du3CwXQPoKVb4pKnfk0/4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOXdIalZBZ0tqWElTVG51
            Sm5TMGh1cTJyNGE5eHdHTWNCRlp2ZmR4UEVRClowdWl5S2NnaVlBcFkrZlRqd1h5
            MXA3WEtScUpRYUpkV0JlbU1SM21LL0EKLS0tIGozR3lTYndsOEZoUjFndFlWUDVB
            cm1GTmxwUmhhWGNoVGFnVDNBUzZqQ2MKkUO/0V55i8B5EbZqXyhxTmkgkJBFehp8
            t6tSOQBxAxsezrY5eTnpFK23Y3LZjK15tfAQZqbeXua6UNc5ipJo1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T18:04:36Z"
    mac: ENC[AES256_GCM,data:z/eQACGhc8srX19jSZLqwLq/k8nOBWZ1sdVd5Sp7mI/6NHUcx2lCllhhxEbL7cGvjjgPDQvPh29wDjkcC8sxF3uWVn5JJey1AeJt2c1dGgxwo7Zm3+w3t2RiuMewFWDPiGRFUaj0x1F3FJknwQtR7AgYJFzNpYoSTYTuoX/Y2jg=,iv:d3V6dM91It7W5cpcK5J0LmlwzYQnT/7kt2P5fHE+tvU=,tag:w7RbPIEjVuAeVanfz91OEw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
