apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OV9nIoo3G/bEJX0tINn6X7k0JgZi+IN2JjkULNOXqJHw4cSTSibnuRM6qz9Z2U6icPWpkOqaptkB8kT5x8V6p2Xvurm4xdMDCeVWUc1u7/IJPamiZ6P3H3TdXYrNBPcgSgrRZZ6+Lkzszqh5SH2EUMkz2TBuv635Jq/4yzJcelU/SqRXqfGwGIS9rAq1dt2wOVAPjKEZHTEcjtaT8Jzn/eAPfVTzz7xicTMUtfYJWjcWmEWC3KYTSXsfEkwHJ2B2MiG0sdP7pOkxNcBlI9lMByDt0Osh5230dyGnic2Zdfc5Qz/lmIbtJPP70LoRnW0ILUzLqzxzxLLu7x4NQlfW5yd/4UeQPU48xbr7dzimiNB7RHF5LOt4RnpzofwMOqhr,iv:F1IdwrUC49gCpBsKD2MVYH6pg/QmHZpMFPZdq5CTW30=,tag:6NHVcz4qN1HEyxzlECDRlQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:DIIyvZ+jVo31Uej4niXft7Kgc5ejyenQ0N2eotNtcTOiLelrRertKOy4tSnfWnsE/0py015buJ2f93TwGymTHZC4vyBVT0LE69wlGGG8OXOTZLPAFSiMWdnFElWIZtjfdIF9Dbh/S9rFozxjhOvxbw6rf8kNP4Dnl5EqWYXU2Xm3edT5WpIC/F7uMTHWujTWsmjm9CxTFsQCVyeFSfK0oKOMN9KwvrkVzurIT3cjKVHiF1A9nRY6YdOcBMe4zsZ86YvHNyKCeswUg8DwBw==,iv:y+SNDd6BGDqCRUPYIhywDj7Tj2SWBvwMt2IcLw4NnTQ=,tag:EbEP3NbkfF8VpMqM3DMV0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:OVpi/gNdXfzcI9xrVrFNX4WgvvUqzSYIDY83gHau5DksomcRkT6QM9l3HUWBrVIacoKh94Lfy+AqVlqUsVZUX5UGi00ChlJCvfPuT9gkRvGFOubR0hbU6+VVFcETYVhMeYnGZ74CuZeuceO0rNaMNWr3LZ2c8yTFzBKYZhRVE+rXbXv+UO1cPUpTdpPDih+H/AIQLzgIX6v71+rY+PQ/Ds4TEeDkXFuO0Bd2,iv:noXXx7R0k0/6btG34KP6FSLEEHeDh/JqI08kHfUuk/A=,tag:rNfFcDDbasRjVmdt3aMsow==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fs9hd9ex63f4yc9l80knzfsa42gnhjcerz2ldyz7v780pefunv4qf8v8ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RmNINFBkREwrSVFYcncv
            TDhzUDIvMzQ3MXQ3dnR3QlduNFlVSWtKUUdrCkZLLy9jVktGeU9FWW5hbkhNTTBk
            VU83ZVFBYVFpek9uQ0kxaU5aS0hSOW8KLS0tIGR3cTJtZVpEcC9pYnhqUTU2ekFN
            bURMR3F5cjBWb0lXak5yTXV3TXAwSUUK7V+ryuGNqQV+IoZHHsQmHwwJJhZojH+g
            dQspI8jNw+vOtTjfvn4JvMHaXjpNn0cFYKrltfKiACLD6Xpxks8XwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T06:54:48Z"
    mac: ENC[AES256_GCM,data:1WghArD6Bcpg1SszkCbRY31EfSKegVOEb3Dwz1GJqPWBoM34Y9n5VHcj/R3Y0etia1w2R7xvvSsdKflTw7vexvlw7+zZdsZWAOPmUvyiyXPuJfJeHh0CJEZwyvj09cDXUAM7adT4nE+4UQcBAn2rHvLzffRylzZ51vD4eHJIksk=,iv:7QY3HrdASt5u5IIJooJbPAPAGqlCajL/mCn2VlngnSM=,tag:X9N0SFeL6hWYwbnpxw8ioQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
