apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-whisper
  namespace: wyoming-whisper
spec:
  interval: 15m
  chart:
    spec:
      chart: wyoming-whisper
      version: 7.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Asia/Yekaterinburg
    wyoming_whisper:
      language: ru
      model: dvislobokov/faster-whisper-large-v3-turbo-russian
      beam_size: 1
    resources:
      limits:
        nvidia.com/gpu: 1
