apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wyoming-whisper-gpu
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/wyoming-whisper-gpu/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

