# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache-webdav
  namespace: apache-webdav
spec:
  interval: 15m
  chart:
    spec:
      chart: apache-webdav
      version: 8.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: apache-webdav
  values:
    TZ: Asia/Yekaterinburg
    persistence:
      data:
        type: nfs
        server: ${NFS_SERVER}
        path: /mnt/big-one/duplicati-backups
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          certManager:
            enabled: true
            certificateIssuer: fiveoseven
        hosts:
          - host: wdav.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # ANONYMOUS_METHODS: ""
                # AUTH_TYPE: Basic
                LOCATION: /duplicatibackups
                PASSWORD: ${WEBDAV_PASSWORD}
                # PUMASK: "0000"
                # REALM: WebDAV-Login
                # SERVER_NAMES: localhost
                # SSL_CERT: ""
                USERNAME: ${WEBDAV_USER}
