---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librespeed
  namespace: librespeed
spec:
  interval: 15m
  chart:
    spec:
      chart: librespeed
      version: 16.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: true
        integrations:
          metallb:
            enabled: true
            sharedKey: shared-ip-key
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          certManager:
            enabled: true
            certificateIssuer: fiveoseven
        hosts:
          - host: speed.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
