apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-extr
  namespace: portainer-extr
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: portainer-extr
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: portainer.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: ""
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: Portainer (external)
            group: Administration
            widget:
              enabled: false
          traefik:
            allowCors: false
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    service:
      main:
        enabled: true
        externalIP: ${DOCKER_VM_IP}
        ports:
          main:
            enabled: true
            port: 9443
            protocol: https
        type: ExternalIP
        useSlice: false
