# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer-extr
  namespace: portainer-extr
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: portainer-extr
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: portainer.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: Portainer (external)
            group: Administration
            widget:
              enabled: false
    service:
      main:
        enabled: true
        externalIP: ${DOCKER_VM_IP}
        ports:
          main:
            enabled: true
            port: 9443
            protocol: https
        type: ExternalIP
        useSlice: false
