apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: homepage
  values:
    TZ: Asia/Yekaterinburg
    workload:
      main:
        podSpec:
          initContainers:
            init-config:
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /app/config
                  echo "Using bookmarks.yaml from helm release"
                  cp -f /dummy-config/bookmarks.yaml /app/config/bookmarks.yaml
                  echo "Config file copied"
                  echo "Using services.yaml from helm release"
                  cp -f /dummy-config/services.yaml /app/config/services.yaml
                  echo "Config file copied"
                  echo "Using settings.yaml from helm release"
                  cp -f /dummy-config/settings.yaml /app/config/settings.yaml
                  echo "Config file copied"
                  echo "Using widgets.yaml from helm release"
                  cp -f /dummy-config/widgets.yaml /app/config/widgets.yaml
                  echo "Config file copied"
                  echo "Using custom.css from helm release"
                  cp -f /dummy-config/custom.css /app/config/custom.css
                  echo "Config file copied"
                  echo "Using custom.js from helm release"
                  cp -f /dummy-config/custom.js /app/config/custom.js
                  echo "Config file copied"
    configmap:
      config:
        data:
          bookmarks.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/bookmarks

            - Util: []
          custom.css: ""
          custom.js: ""
          settings.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/settings

            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey
          widgets.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/widgets

            - resources:
                cpu: true
                memory: true
                disk: /

            - search:
                provider: duckduckgo
                target: _blank
          
          services.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/services

            - Media: []
            - Arrrelated: []
            - Administration:
              - Truenas:
                  href: https://truenas.${BASE_DOMAIN}/
                  icon: si-truenas
                  description: The Old Home
                  siteMonitor: https://truenas.${BASE_DOMAIN}/
            - Automation: []
        enabled: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: homepage.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          traefik:
            allowCors: false
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik