apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: homepage
  values:
    TZ: Asia/Yekaterinburg
    configmap:
      config:
        data:
          bookmarks.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/bookmarks

            - Util:
                - Truenas:
                    - abbr: TNS
                      href: https://truenas.${BASE_DOMAIN}/
          custom.css: ""
          custom.js: ""
          settings.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/settings

            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey
          widgets.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/widgets

            - resources:
                cpu: true
                memory: true
                disk: /

            - search:
                provider: duckduckgo
                target: _blank
          
          services.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/services

            - Media: []
            - Arrrelated: []
            - Administration:
              - Truenas:
                  href: https://truenas.${BASE_DOMAIN}/
                  icon: "truenas.png"
                  description: The Old Home
            - Automation: []
        enabled: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: homepage.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          traefik:
            allowCors: false
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik