# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: audiobookshelf
      version: 12.15.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: audiobookshelf
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.audiobookshelf
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: abooks.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              custom:
                key: ${AUDIOBOOKSHELF_API_KEY}
      external:
        enabled: true
        ingressClassName: external
        hosts:
          - host: abooks.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: false
            group: Media
            widget:
              custom:
                key: ${AUDIOBOOKSHELF_API_KEY}
    persistence:
      audiobooks:
        enabled: true
        mountPath: /audiobooks
        path: /mnt/wide-one/media/torrents/audiobooks
        server: ${NFS_SERVER}
        type: nfs
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      metadata:
        volsync:
          - credentials: backup
            name: backup-meta
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
