apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 22.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: sonarr
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: sonarr
        encrKey: "${VOLSYNC_ENCR_KEY_1//F/#}${VOLSYNC_ENCR_KEY_2}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: sonarr.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        mountPath: /content
        path: /mnt/big-one/media
        readOnly: false
        server: ${NFS_SERVER}
        type: nfs
