apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 12.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: cloudflared
  values:
    TZ: Asia/Yekaterinburg
    release_name: cloudflared
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TUNNEL_TOKEN: eyJhIjoiY2U5M2I3Mzk2ODA5M2MxYzk1ZTRhMGE2YjcxNDAzODUiLCJ0IjoiYTlhYzVmNWUtMDk1Ny00ZThjLWE2MmItNmRhOWM1YTY5MjBhIiwicyI6IlpXTTFORGhsWlRjdE1XUTNaaTAwWVdVMUxUZzFNMlF0WlRaaVl6TTRPVGs0T1RVMSJ9
