apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 13.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: cloudflared
  values:
    TZ: Asia/Yekaterinburg
    release_name: cloudflared
    podOptions:
      hostUsers: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
