apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: flux-system
spec:
  type: github
  address: ${GITHUB_REPO_URL}
  secretRef:
    name: github-alert-token