# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-alert-token
  namespace: flux-system
data:
  token: ${GITHUB_STATUSES_TOKEN}