# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: navidrome
      version: 22.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: navidrome
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.navidrome
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: music.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
      local:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: music.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              custom:
                user: ${NAVIDROME_USER}
                token: ${NAVIDROME_TOKEN}
                salt: ${NAVIDROME_SALT}
    persistence:
      data:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      music:
        path: /mnt/wide-one/media/media/music
        server: ${NFS_SERVER}
        type: nfs
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ND_ENABLETRANSCODINGCONFIG: false
                ND_LASTFM_ENABLED: "true"
                ND_LASTFM_LANGUAGE: ru
                ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
                ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
                ND_MUSICFOLDER: /music
                ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
                ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
