# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 19.47.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: immich
  values:
    TZ: Asia/Yekaterinburg
    immich:
      mlImageType: mlCudaImage
    podOptions:
      runtimeClassName: "nvidia"
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.immich
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
      backup-cnpg:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.immich.cnpg
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-cnpg
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: immich.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          # - host: immich.${LOCAL_DOMAIN}
          #   paths:
          #     - path: /
          #       pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              custom:
                key: ${IMMICH_API_KEY}
              version: 2
    persistence:
      library:
        path: /mnt/big-one/immich-photos/library
        server: ${NFS_SERVER}
        type: nfs
      uploads:
        path: /mnt/big-one/immich-photos/uploads
        server: ${NFS_SERVER}
        type: nfs
      backups: # extra dataset for this?
        path: /mnt/big-one/immich-photos/backups
        server: ${NFS_SERVER}
        type: nfs
      profile:
        path: /mnt/fast-one/immich-cache/profiles
        server: ${NFS_SERVER}
        type: nfs
      thumbs:
        path: /mnt/fast-one/immich-cache/thumbnails
        server: ${NFS_SERVER}
        type: nfs
      video:
        path: /mnt/big-one/immich-photos/video
        server: ${NFS_SERVER}
        type: nfs
      mlcache:
        targetSelector:
          machinelearning:
            machinelearning:
              mountPath: /mlcache
          main:
            codeserver:
              mountPath: /mlcache
        type: pvc
      legacy-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo-archive/legacy-library
        mountPath: /mnt/legacy-library
        server: ${NFS_SERVER}
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}
      older-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo/originals
        mountPath: /mnt/older-library
        server: ${NFS_SERVER}
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}
    cnpg:
      main:
        mode: recovery
        backups:
          enabled: true
          revision: "2"
          credentials: backup-cnpg
        recovery:
          revision: "1"
          credentials: backup-cnpg
    resources:
      limits:
        cpu: 8000m
        memory: 8Gi
        nvidia.com/gpu: 1
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          integrations:
            certManager:
              enabled: true
              certificateIssuer: fiveoseven
          hosts:
            - host: code-immich.${LOCAL_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
