# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 19.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: immich
  values:
    TZ: Asia/Yekaterinburg
    immich:
      mlImageType: mlCudaImage
    workload:
      machinelearning:
        podSpec:
          runtimeClassName: "nvidia"
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.immich
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
      backup-cnpg:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.immich.cnpg
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-cnpg
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: immich.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          # - host: immich.${LOCAL_DOMAIN}
          #   paths:
          #     - path: /
          #       pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              key: ${IMMICH_API_KEY}
              version: 2
    persistence:
      library:
        path: /mnt/big-one/immich-photos/library
        server: ${NFS_SERVER}
        type: nfs
      uploads:
        path: /mnt/big-one/immich-photos/uploads
        server: ${NFS_SERVER}
        type: nfs
      backups: # extra dataset for this?
        path: /mnt/big-one/immich-photos/backups
        server: ${NFS_SERVER}
        type: nfs
      # profile: # ??? no idea
        # volsync: # maybe?
        #   - credentials: backup
        #     dest:
        #       enabled: true
        #     name: backup
        #     src:
        #       enabled: true
        #     type: restic
      # keep thumbs in pvc
      # thumbs: # or put them to hdd? ssd prolly better
      #   path: /mnt/fast-one/immich-thumbs # todo: create
      #   server: ${NFS_SERVER}
      #   type: nfs
      video:
        path: /mnt/big-one/immich-photos/video
        server: ${NFS_SERVER}
        type: nfs
      legacy-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo-archive/legacy-library
        mountPath: /mnt/legacy-library
        server: ${NFS_SERVER}
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}
      older-library:
        type: nfs
        enabled: true
        readOnly: false
        path: /mnt/big-one/photo/originals
        mountPath: /mnt/older-library
        server: ${NFS_SERVER}
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}
    cnpg:
      main:
        backups:
          enabled: true
          credentials: backup-cnpg
        recovery:
          credentials: backup-cnpg
    resources:
      limits:
        cpu: 8000m
        nvidia.com/gpu: 1
