# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-operator
  namespace: gpu-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: gpu-operator
      version: 24.9.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # So you are telling me I could've just skip all the faff
    # with talos drivers/kernel modules/toolkit
    # and just NOT disable this?
    driver:
      enabled: false
    toolkit:
      enabled: false
    nfd:
      enabled: false
