apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 18.11.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: prowlarr
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: prowlarr
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: prowlarr.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Arrrelated
            widget:
              custom:
                key: ${PROWLARR_API_KEY}
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
