apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: browserless-chrome
  namespace: browserless-chrome
spec:
  interval: 15m
  chart:
    spec:
      chart: browserless-chrome
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    TZ: Asia/Yekaterinburg
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: browserless.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TOKEN: ${BRLESS_TOKEN}
              probes:
                liveness:
                  path: /?token=${BRLESS_TOKEN}
                readiness:
                  path: /?token=${BRLESS_TOKEN}
                startup:
                  path: /?token=${BRLESS_TOKEN}
