apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  interval: 15m
  chart:
    spec:
      chart: satisfactory
      version: 12.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: satisfactory
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.satisfactory
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
