---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    clusterIssuer:
      selfSigned:
        enabled: true
        name: "selfsigned"
      ## Remove these if you do NOT want to use clusterissuer
      ACME:
        - name: fiveoseven
          cfapitoken: "${CLOUDFLARE_TOKEN}"
          email: "${EMAIL}"
          server: https://acme-v02.api.letsencrypt.org/directory
          type: cloudflare
        - name: fiveoseven-staging
          cfapitoken: "${CLOUDFLARE_TOKEN}"
          email: "${EMAIL}"
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          type: cloudflare
    ## Remove these if you do NOT want to use clusterissuer
    clusterCertificates:
      # Namespaces in which the certificates must be available
      # Accepts comma-separated regex expressions
      replicationNamespaces: '.*'
      certificates:
        - name: basedomain-wildcard
          enabled: true
          certificateIssuer: fiveoseven
          hosts:
            - ${BASE_DOMAIN}
            - '*.${BASE_DOMAIN}'
        - name: localdomain-wildcard
          enabled: true
          certificateIssuer: fiveoseven
          hosts:
            - ${LOCAL_DOMAIN}
            - '*.${LOCAL_DOMAIN}'