apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: nvidia-gpu-operator
spec:
  interval: 15m
  releaseName: nvidia-gpu-operator
  chart:
    spec:
      chart: gpu-operator
      version: 26.7.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    driver:
      enabled: false
    toolkit:
      enabled: false
    hostPaths:
      driverInstallDir: /usr/local
    nfd:
      enabled: false
    migManager:
      enabled: false
    devicePlugin:
      # can be removed on talos@1.14
      env:
        - name: NVIDIA_CDI_HOOK_PATH
          value: /usr/local/bin/nvidia-cdi-hook
      config:
        name: device-plugin-config
        create: true
        data:
          default: |-
            version: v1
            sharing:
              timeSlicing:
                renameByDefault: false
                resources:
                  - name: nvidia.com/gpu
                    replicas: 5
