apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: universal-media-server
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: universal-media-server
      version: 7.2.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: universal-media-server
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: universal-media-server
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: ums.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup-config
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
      media:
        enabled: true
        path: /mnt/big-one/media/torrents/3d-movie
        server: ${NFS_SERVER}
        type: nfs
    service:
      main:
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
        sharedKey: shared-ip-key
      api:
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
        sharedKey: shared-ip-key
      sub:
        loadBalancerIP: ${EXTRA_LB_IP}
        type: LoadBalancer
        sharedKey: shared-ip-key
    resources:
      limits:
        cpu: 8000m
        # nvidia.com/gpu: 1
