apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett-lidarr
  namespace: jackett-lidarr
spec:
  interval: 15m
  chart:
    spec:
      chart: jackett
      version: 23.3.68
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: jackett-lidarr
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.jackett-lidarr
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    ingress:
      main:
        enabled: true
        hosts:
          - host: jackett-lidarr.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            name: Jackett (for Lidarr)
            group: Arrrelated
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: local-only
                namespace: traefik
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
