# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Asia/Yekaterinburg
    homeassistant:
      trusted_proxies: ["172.16.0.0/16"]
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.homeassistant
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
      backup-cnpg:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.homeassistant.cnpg
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup-cnpg
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    persistence:
      config:
        volsync:
          - credentials: backup
            name: backup
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
    cnpg:
      main:
        backups:
          enabled: true
          credentials: backup-cnpg
        recovery:
          credentials: backup-cnpg
    ingress:
      main:
        enabled: true
        hosts:
          - host: ha.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local-only
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: fiveoseven
          homepage:
            enabled: true
            group: Automation
            widget:
              key: ${HA_API_KEY}
    addons:
      codeserver:
        enabled: true
        container:
          resources:
            limits:
              cpu: 3333m
              memory: 3333Mi
        service:
          enabled: true
          ports:
            codeserver:
              enabled: true
              port: 12345
              targetPort: 12345
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: local-only
                  namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: fiveoseven
          hosts:
            - host: code.ha.${LOCAL_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
