apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: huginn-extr
  namespace: huginn-extr
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 14.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: huginn-extr
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: huginn.***REMOVED***
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Util
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: cloud-only
                namespace: traefik
    service:
      main:
        enabled: true
        externalIP: ${DOCKER_VM_IP}
        ports:
          main:
            enabled: true
            port: 3000
            protocol: http
        type: ExternalIP
        useSlice: false
