# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 15m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 14.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: zigbee2mqtt
  values:
    TZ: Asia/Yekaterinburg
    credentials:
      backup:
        accessKey: ${VOLSYNC_ACCESS_KEY}
        bucket: backups.zigbee2mqtt
        encrKey: "${VOLSYNC_ENCR_KEY}"
        name: backup
        path: ""
        secretKey: ${VOLSYNC_SECRET_KEY}
        type: s3
        url: ${VOLSYNC_URL}
    persistence:
      data:
        volsync:
          - credentials: backup
            dest:
              enabled: true
            name: backup
            src:
              enabled: true
            type: restic
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: z2m.${LOCAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: fiveoseven
            enabled: true
          homepage:
            enabled: true
            group: Automation
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                USE_CUSTOM_CONFIG_FILE: false
    addons:
      codeserver:
        enabled: true
        container:
          resources:
            limits:
              cpu: 3333m
              memory: 3333Mi
        service:
          enabled: true
          ports:
            codeserver:
              enabled: true
              port: 12345
              targetPort: 12345
        ingress:
          enabled: true
          ingressClassName: internal
          integrations:
            certManager:
              enabled: true
              certificateIssuer: fiveoseven
          hosts:
            - host: code.z2m.${LOCAL_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
