apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - audiobookshelf/ks.yaml
  - flacon/ks.yaml
  - jellyfin/ks.yaml
  - lidarr/ks.yaml
  - navidrome/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
